--[[
    Imperial Export for FiveM
DO NOT EDIT THIS FILE UNLESS YOU KNOW WHAT YOUR DOING!
]]--

function GenerateRandomString(length)
    local charset = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
    local result = ""
    for i = 1, length do
        local rand = math.random(1, #charset)
        result = result .. charset:sub(rand, rand)
    end
        return result
end

function GenerateDate(future)
    local now = os.time()
    local months = math.random(2, 24)
    local offset = months * 30 * 24 * 60 * 60 -- approx months in seconds
    local target = future and (now + offset) or (now - offset)
    local d = os.date("*t", target)
    return ("%02d/%02d/%d"):format(d.month, d.day, d.year)
end

--trys to find the discord ID
local discordIdCache = {}

function getDiscordId(src)
    if src == nil then return false end

    if discordIdCache[src] then
        return discordIdCache[src]
    end

    local identifiers = GetPlayerIdentifiers(src)
    for _, v in pairs(identifiers) do
        if string.sub(v, 1, 8) == "discord:" then
            local discordId = string.gsub(v, "discord:", "")
            discordIdCache[src] = discordId
            return discordId
        end
    end
    return false
end

AddEventHandler('playerDropped', function()
    discordIdCache[source] = nil
end)
